version: "3"

volumes:
  database_volume: {}
  
services:
  web:
    image: python-init
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      SEPARATE_WORKER_PROCESS: 'True'
      DATABASE_URL: postgres://postgres:pass@database/postgres
    stdin_open: true
    tty: true
#  worker:
#    image: python-init
#    build: .
#    env_file: .env
#    stdin_open: true
#    tty: true
#    entrypoint: gunicorn --threads 10 --bind 0.0.0.0:5000  main.workers.master:app
#    ports:
#      - 5000:5000
  database:
    image: postgres:12
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
