version: "3"

volumes:
  database_volume: {}
  
services:
  web:
    image: futurecoder
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      DATABASE_URL: postgres://postgres:pass@database/postgres
      DEBUG: 'False'
      DISABLE_HTTPS: 'True'
    stdin_open: true
    tty: true
  database:
    image: postgres:12
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
