version: "3"

volumes:
  database_volume: {}
  
services:
  web:
    image: python-init
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      SEPARATE_WORKER_PROCESS: 'True'
      CLOUDAMQP_URL: amqp://rabbitmq
      DATABASE_URL: postgres://postgres:pass@database/postgres
    stdin_open: true
    tty: true
    depends_on:
      - rabbitmq
  worker:
    image: python-init
    build: .
    env_file: .env
    stdin_open: true
    tty: true
    entrypoint: python -m main.worker
    environment:
      SEPARATE_WORKER_PROCESS: 'True'
      CLOUDAMQP_URL: amqp://rabbitmq
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  database:
    image: postgres:12
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
