version: "3"

volumes:
  database_volume: {}
  
services:
  web:
    image: futurecoder
    build: .
    ports:
      - 3000:3000
    env_file: .env
    environment:
      SEPARATE_WORKER_PROCESS: 'True'
      DATABASE_URL: postgres://postgres:pass@database/postgres
      DEBUG: 'False'
      MASTER_URL: http://master:5000/
    stdin_open: true
    tty: true
  master:
    image: futurecoder
    build: .
    env_file: .env
    environment:
      MONITOR_ACTIVE: 'True'
    stdin_open: true
    tty: true
    entrypoint: ./master_server.sh
    ports:
      - 5000:5000
  database:
    image: postgres:12
    volumes:
      - database_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
