[tool.poetry]
name = "book"
version = "0.1.0"
description = ""
authors = ["Alex Hall <alex.mojaki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^2.2.7"
django-sass-processor = "^0.7.4"
libsass = "^0.19.4"
django-compressor = "^2.3"
markdown = "^3.1.1"
astcheck = "^0.2.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
