[tool.poetry]
name = "book"
version = "0.1.0"
description = ""
authors = ["Alex Hall <alex.mojaki@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
Django = "^2.2.7"
django-sass-processor = "^0.7.4"
libsass = "^0.19.4"
django-compressor = "^2.3"
markdown = "^3.1.1"
astcheck = "^0.2.5"
asttokens = "^2.0.3"
littleutils = "^0.2.1"
snoop = "^0.2.4"
birdseye = "^0.8.3"
django-allauth = "^0.41.0"
django-user-agents = "^0.4.0"
gevent = {version = "^1.4", optional = true}
gunicorn = {version = "^19.9", optional = true}
pika = {version = "^1.1.0", optional = true}

[tool.poetry.extras]
production = ["gevent", "gunicorn", "pika"]

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
